#ifndef CONTINENTS_H_
#define CONTINENTS_H_

enum Continents 
{
  NO_CONTINENT = 1,	//1
  SORPIGAL_CONTINENT,	//2
  FAR_REACH,		//3	
  DIAMOND_ISLE,		//4
  UNDERDARK,    	//5
  BEHIND_THE_MIRROR,	//6
  PLANES_OF_EXISTANCE,	//7
  FORBIDDEN_ISLAND,	//8
  ORIGINATION, //9
  OTHER_CONTINENT,	//10
  MAX_CONTINENTS 	//for iteration
};

#endif